spring.application.name=chat-app
server.port=8080
server.address=0.0.0.0

spring.datasource.url=jdbc:postgresql://localhost:5432/Chat-App
spring.datasource.username=postgres
spring.datasource.password=log3in7dat

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#JWT Secret key
jwt.secret=2f8e2837a191f560408df9d57832b0480fa0b3faa2c4fe0b9a015bd8af41e807

#Send Mail Config
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=bankingsystem25@gmail.com
spring.mail.password=xvpopnqyfihjnviy
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
